/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'Project_53a367a' 
 * Target:  'HT32' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ht32f5xxxx_01.h"



#endif /* RTE_COMPONENTS_H */
